### ISSUE TITLE
Swagger UI component for endpoints with @PathVariable require configuration of attribute 'name'

### ISSUE THREAD

**Issue by callmemarv** [qaware/openapi-generator-for-spring#16]
Given the following controller method:

``` java
@Operation(summary = "Fetch resource by ID")
@GetMapping(value = "/{resourceId}")
public MyResourceDto fetchResource(@PathVariable ResourceId resourceId) {
    ...
}
```

The Swagger UI component for this method looks fine but it does not contain the field name _resourceId_, only its type. If I enter a value into the input field the value immediately disappears. If I click on the execute button no request is fired.

Configuring the name attribute of @PathVariable fixes the problem.

``` java
@PathVariable(name = "resourceId") ResourceId resourceId 
```

Is there a way to make configuring this unnecessary?

**Comment by neiser** [comment]
There should be, let me check.

**Comment by callmemarv** [comment]
Adding the `-parameters` flag did the trick. 🎉
