### ISSUE TITLE
Enable CSRF for swagger-ui

### ISSUE THREAD

**Issue by mlux86** [qaware/openapi-generator-for-spring#19]
Right now, the OpenAPI Generator for Spring does not respect CSRF cookies, i.e. the CSRF/CSRF Token set in a cookie is not added to the request headers.

In order to be able to use swagger-ui in applications that support CSRF, please enable it in swagger-ui, too.

Related to this: https://github.com/swagger-api/swagger-ui/issues/1380

**Comment by neiser** [comment]
see also springfox/springfox#2434
