### ISSUE TITLE
Basic Authentication Schema not applying on generated Swagger SecurityScheme

### ISSUE THREAD

**Issue by jakMoeller** [qaware/openapi-generator-for-spring#20]
Hey there, first of all: Nice Project, I really like the idea of not having to stick to the old-fashioned structuring of springfox and co. keep it up!

I've wondered wether I am doing anything wrong when instantiating a SecuritySchema through the given Annotation
```java
@SecurityScheme(
        name = "Basic Authentication",
        type = SecuritySchemeType.HTTP,
        scheme = "basic"
)
```
I have noticed that the Swagger UI does indeed show the Authorization, but apparently the calls to the service do not propagate. Is this indended/not yet implemented or is this something that is going wrong on my side?

All the best!

**Comment by neiser** [comment]
Hi @jakMoeller 

Sorry for replying only now, I somehow wasn't notifed by email although I'm watching this repo on Github :confused: 

I'll look into this soon and give feedback.

**Comment by neiser** [comment]
@jakMoeller I've checked it and I think you're missing an additional `@SecurityRequirement` annotation. Full example would be:
```
@RestController
@SecurityScheme(
        name = "BasicAuthentication",
        type = SecuritySchemeType.HTTP,
        scheme = "basic"
)
@SecurityRequirement(name = "BasicAuthentication")
public class App41Controller {
    @GetMapping
    public String mapping1() {
        return "Hello World";
    }
}
```

This way, you actually require the security on that operation and then Swagger UI also sends the `Authorization: Basic ...` header (I've seen that within the browser's network inspection).

Does this solve it for you?

**Comment by neiser** [comment]
Closing this issue. Please re-open if you think it's still not solved for you.
